// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID               int32
	Title            string
	DescriptionShort string
	DescriptionLong  string
	RepoUrl          pgtype.Text
	LiveUrl          pgtype.Text
	VideoUrl         pgtype.Text
	CreatedAt        pgtype.Timestamptz
	Featured         bool
}

type ProjectImage struct {
	ID        int32
	ProjectID int32
	ImageUrl  string
}

type ProjectTechnology struct {
	ProjectID    int32
	TechnologyID int32
}

type Technology struct {
	ID       int32
	Name     string
	IconSlug string
}

type User struct {
	ID           int32
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
