// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const associateProjectTechnology = `-- name: AssociateProjectTechnology :exec
INSERT INTO project_technology (
    project_id, technology_id
) VALUES (
    $1, $2
)
`

type AssociateProjectTechnologyParams struct {
	ProjectID    int32
	TechnologyID int32
}

func (q *Queries) AssociateProjectTechnology(ctx context.Context, arg AssociateProjectTechnologyParams) error {
	_, err := q.db.Exec(ctx, associateProjectTechnology, arg.ProjectID, arg.TechnologyID)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO project (
    title, translation_key, repo_url, live_url, video_url, featured
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, title, translation_key, repo_url, live_url, video_url, created_at, featured
`

type CreateProjectParams struct {
	Title          string
	TranslationKey string
	RepoUrl        pgtype.Text
	LiveUrl        pgtype.Text
	VideoUrl       pgtype.Text
	Featured       bool
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Title,
		arg.TranslationKey,
		arg.RepoUrl,
		arg.LiveUrl,
		arg.VideoUrl,
		arg.Featured,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TranslationKey,
		&i.RepoUrl,
		&i.LiveUrl,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.Featured,
	)
	return i, err
}

const createProjectImage = `-- name: CreateProjectImage :one
INSERT INTO project_images (
    project_id, image_url
) VALUES (
    $1, $2
) RETURNING id, project_id, image_url
`

type CreateProjectImageParams struct {
	ProjectID int32
	ImageUrl  string
}

func (q *Queries) CreateProjectImage(ctx context.Context, arg CreateProjectImageParams) (ProjectImage, error) {
	row := q.db.QueryRow(ctx, createProjectImage, arg.ProjectID, arg.ImageUrl)
	var i ProjectImage
	err := row.Scan(&i.ID, &i.ProjectID, &i.ImageUrl)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM project
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT 
    p.id, p.title, p.translation_key, p.repo_url, p.live_url, p.video_url, p.created_at, p.featured,
    COALESCE(
        (SELECT json_agg(item) FROM (SELECT id, image_url FROM project_images WHERE project_id = p.id) item), 
        '[]'::json
    ) AS images,
    COALESCE(
        (SELECT json_agg(tech) FROM (
            SELECT t.id, t.name, t.icon_slug FROM technology t 
            JOIN project_technology pt ON t.id = pt.technology_id 
            WHERE pt.project_id = p.id
        ) tech), 
        '[]'::json
    ) AS technologies
FROM project p
WHERE p.id = $1 LIMIT 1
`

type GetProjectRow struct {
	ID             int32
	Title          string
	TranslationKey string
	RepoUrl        pgtype.Text
	LiveUrl        pgtype.Text
	VideoUrl       pgtype.Text
	CreatedAt      pgtype.Timestamptz
	Featured       bool
	Images         interface{}
	Technologies   interface{}
}

func (q *Queries) GetProject(ctx context.Context, id int32) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TranslationKey,
		&i.RepoUrl,
		&i.LiveUrl,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.Featured,
		&i.Images,
		&i.Technologies,
	)
	return i, err
}

const listFeaturedProjects = `-- name: ListFeaturedProjects :many
SELECT 
    p.id, p.title, p.translation_key, p.repo_url, p.live_url, p.video_url, p.created_at, p.featured,
    COALESCE(
        (SELECT json_agg(item) FROM (SELECT id, image_url FROM project_images WHERE project_id = p.id) item), 
        '[]'::json
    ) AS images,
    COALESCE(
        (SELECT json_agg(tech) FROM (
            SELECT t.id, t.name, t.icon_slug FROM technology t 
            JOIN project_technology pt ON t.id = pt.technology_id 
            WHERE pt.project_id = p.id
        ) tech), 
        '[]'::json
    ) AS technologies
FROM project p
WHERE p.featured = true
ORDER BY p.created_at DESC
`

type ListFeaturedProjectsRow struct {
	ID             int32
	Title          string
	TranslationKey string
	RepoUrl        pgtype.Text
	LiveUrl        pgtype.Text
	VideoUrl       pgtype.Text
	CreatedAt      pgtype.Timestamptz
	Featured       bool
	Images         interface{}
	Technologies   interface{}
}

func (q *Queries) ListFeaturedProjects(ctx context.Context) ([]ListFeaturedProjectsRow, error) {
	rows, err := q.db.Query(ctx, listFeaturedProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeaturedProjectsRow
	for rows.Next() {
		var i ListFeaturedProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TranslationKey,
			&i.RepoUrl,
			&i.LiveUrl,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.Featured,
			&i.Images,
			&i.Technologies,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectImages = `-- name: ListProjectImages :many
SELECT id, project_id, image_url FROM project_images
WHERE project_id = $1
`

func (q *Queries) ListProjectImages(ctx context.Context, projectID int32) ([]ProjectImage, error) {
	rows, err := q.db.Query(ctx, listProjectImages, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectImage
	for rows.Next() {
		var i ProjectImage
		if err := rows.Scan(&i.ID, &i.ProjectID, &i.ImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTechnologies = `-- name: ListProjectTechnologies :many
SELECT t.id, t.name, t.icon_slug FROM technology t
JOIN project_technology pt ON t.id = pt.technology_id
WHERE pt.project_id = $1
`

func (q *Queries) ListProjectTechnologies(ctx context.Context, projectID int32) ([]Technology, error) {
	rows, err := q.db.Query(ctx, listProjectTechnologies, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Technology
	for rows.Next() {
		var i Technology
		if err := rows.Scan(&i.ID, &i.Name, &i.IconSlug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT 
    p.id, p.title, p.translation_key, p.repo_url, p.live_url, p.video_url, p.created_at, p.featured,
    COALESCE(
        (SELECT json_agg(item) FROM (SELECT id, image_url FROM project_images WHERE project_id = p.id) item), 
        '[]'::json
    ) AS images,
    COALESCE(
        (SELECT json_agg(tech) FROM (
            SELECT t.id, t.name, t.icon_slug FROM technology t 
            JOIN project_technology pt ON t.id = pt.technology_id 
            WHERE pt.project_id = p.id
        ) tech), 
        '[]'::json
    ) AS technologies
FROM project p
ORDER BY p.created_at DESC
`

type ListProjectsRow struct {
	ID             int32
	Title          string
	TranslationKey string
	RepoUrl        pgtype.Text
	LiveUrl        pgtype.Text
	VideoUrl       pgtype.Text
	CreatedAt      pgtype.Timestamptz
	Featured       bool
	Images         interface{}
	Technologies   interface{}
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TranslationKey,
			&i.RepoUrl,
			&i.LiveUrl,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.Featured,
			&i.Images,
			&i.Technologies,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
