// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProjectWithTechnologies = `-- name: GetProjectWithTechnologies :many
SELECT 
    p.id as project_id, p.title, p.description_short, p.featured,
    t.id as tech_id, t.name as tech_name, t.icon_slug
FROM project p
LEFT JOIN project_technology pt ON p.id = pt.project_id
LEFT JOIN technology t ON pt.technology_id = t.id
WHERE p.id = $1
`

type GetProjectWithTechnologiesRow struct {
	ProjectID        int32
	Title            string
	DescriptionShort string
	Featured         bool
	TechID           pgtype.Int4
	TechName         pgtype.Text
	IconSlug         pgtype.Text
}

func (q *Queries) GetProjectWithTechnologies(ctx context.Context, id int32) ([]GetProjectWithTechnologiesRow, error) {
	rows, err := q.db.Query(ctx, getProjectWithTechnologies, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectWithTechnologiesRow
	for rows.Next() {
		var i GetProjectWithTechnologiesRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Title,
			&i.DescriptionShort,
			&i.Featured,
			&i.TechID,
			&i.TechName,
			&i.IconSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, title, description_short, description_long, repo_url, live_url, created_at, featured FROM project
ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DescriptionShort,
			&i.DescriptionLong,
			&i.RepoUrl,
			&i.LiveUrl,
			&i.CreatedAt,
			&i.Featured,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
